

const button = document.getElementById('change_content');
const paragraph = document.getElementById('paragraph');

const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Act as if what you do makes a difference. It does. - William James",
    "Quality means doing it right when no one is looking. - Henry Ford",
    "Dream big and dare to fail. - Norman Vaughan",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "If you want to achieve greatness stop asking for permission. - Unknown",
    "The best way to predict the future is to create it. - Peter Drucker",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William B. Sprague",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Life isn’t about getting and having, it’s about giving and being. - Kevin Kruse",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. - Jamie Paolinetti",
    "Nothing is impossible, the word itself says ‘I’m possible’! - Audrey Hepburn",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The harder the conflict, the greater the triumph. - George Washington",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
    "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
    "If you can dream it, you can do it. - Walt Disney",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway. - Eleanor Roosevelt",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Winning isn’t everything, but wanting to win is. - Vince Lombardi",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Don’t be pushed by your problems. Be led by your dreams. - Ralph Waldo Emerson",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "If you can’t explain it simply, you don’t understand it well enough. - Albert Einstein",
    "Do what you can, where you are, with what you have. - Theodore Roosevelt",
    "Stay hungry. Stay foolish. - Steve Jobs",
    "It is never too late to be what you might have been. - George Eliot",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "Definiteness of purpose is the starting point of all achievement. - W. Clement Stone",
    "Either you run the day, or the day runs you. - Jim Rohn",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
    "Do what you love and the money will follow. - Marsha Sinetar",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Courage is resistance to fear, mastery of fear, not absence of fear. - Mark Twain",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Act as if what you do makes a difference. It does. - William James",
    "The best revenge is massive success. - Frank Sinatra",
    "The mind is everything. What you think you become. - Buddha",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "A goal properly set is halfway reached. - Zig Ziglar",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "If you do what you’ve always done, you’ll get what you’ve always gotten. - Tony Robbins",
    "Don’t cry because it’s over, smile because it happened. - Dr. Seuss",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "If you’re going through hell, keep going. - Winston Churchill",
    "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
    "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
    "What you do today can improve all your tomorrows. - Ralph Marston",
    "Action is the foundational key to all success. - Pablo Picasso",
    "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "Everything has beauty, but not everyone can see. - Confucius",
    "What we achieve inwardly will change outer reality. - Plutarch"
];

button.addEventListener('click', function(){
    let randomQuotes = quotes[Math.floor(Math.random() * quotes.length)];
    paragraph.innerText = randomQuotes;
});
